version: "3.0"

services:
  hlds:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/cstrk10:/server/hlds_l/cstrk10
      - ./config/cstrk71:/server/hlds_l/cstrk71
      - ./config/cstrk11r:/server/hlds_l/cstrk11r
    ports:
      - 27015:27015
      - 27015:27015/udp
    command:
      - -port 27015 -game cstrk10 +map de_dust +maxplayers 16